spring:
    application:
        name: demo
    datasource:
        url: jdbc:mysql://localhost:3306/book
        username: book
        password: book
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                temp:
                    use_jdbc_metadata_defaults: false
    flyway:
        baseline-on-migrate: true
        locations: src/main/resources/db/migration/